
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Label labelTimer;
	private global::Gtk.Button buttonStart;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.labelTimer = new global::Gtk.Label ();
		this.labelTimer.Name = "labelTimer";
		this.labelTimer.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.fixed2.Add (this.labelTimer);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.labelTimer]));
		w1.X = 157;
		w1.Y = 48;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.buttonStart = new global::Gtk.Button ();
		this.buttonStart.CanFocus = true;
		this.buttonStart.Name = "buttonStart";
		this.buttonStart.UseUnderline = true;
		this.buttonStart.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.fixed2.Add (this.buttonStart);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.buttonStart]));
		w2.X = 275;
		w2.Y = 196;
		this.Add (this.fixed2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.buttonStart.Clicked += new global::System.EventHandler (this.OnButtonStartClicked);
	}
}
